/* 
 * For license information please see LICENSE.txt
 */
package com.t0ast.xdocroot.ui;

import com.t0ast.swingutils.ui.LinkLabelAddon;
import com.t0ast.xdocroot.config.Config;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author T0astBread
 */
public class SettingsPanel extends javax.swing.JPanel
{
    private Config config;
    private JFileChooser confFileChooser;

    /**
     * Creates new form Settings
     */
    public SettingsPanel()
    {
        initComponents();
        this.confFileChooser = new JFileChooser("C:/xampp/apache/conf/httpd.conf");
        this.confFileChooser.setAcceptAllFileFilterUsed(false);
        this.confFileChooser.addChoosableFileFilter(new FileFilter()
        {
            @Override
            public boolean accept(File f)
            {
                return f.isDirectory() || f.getName().equals("httpd.conf");
            }

            @Override
            public String getDescription()
            {
                return "Apache Module Configuration File (httpd.conf)";
            }
        });
        this.btnConfigFileSelect.addActionListener(evt ->
        {
            if(this.confFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
                this.txtConfigFilePath.setText(this.confFileChooser.getSelectedFile().getAbsolutePath());
        });
        this.btnSave.addActionListener(evt ->
        {
            config.configFilePath = this.txtConfigFilePath.getText();
            btnCancel.getActionListeners()[0].actionPerformed(null);
        });
        this.btnCancel.addActionListener(evt -> SwingUtilities.getWindowAncestor(this).dispose());
        LinkLabelAddon.applyWeblinkTo(this.lblSocialMediaLink, "https://twitter.com/t0astbread");
    }

    public JButton getBtnSave()
    {
        return btnSave;
    }

    public SettingsPanel setConfig(Config config)
    {
        this.config = config;
        this.txtConfigFilePath.setText(config.configFilePath);
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblHeader = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnConfigFileSelect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtConfigFilePath = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblSocialMediaLink = new javax.swing.JLabel();

        lblHeader.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblHeader.setText("Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Apache"));

        btnConfigFileSelect.setText("Select");

        jLabel2.setText("Config File:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfigFilePath)
                .addGap(4, 4, 4)
                .addComponent(btnConfigFileSelect)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConfigFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfigFileSelect))
                .addContainerGap())
        );

        btnCancel.setText("Cancel");

        btnSave.setText("Save");

        lblSocialMediaLink.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSocialMediaLink.setText("Follow me on Twitter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSocialMediaLink)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(0, 0, 0)
                        .addComponent(btnCancel)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel)
                        .addComponent(btnSave))
                    .addComponent(lblSocialMediaLink, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfigFileSelect;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblSocialMediaLink;
    private javax.swing.JTextField txtConfigFilePath;
    // End of variables declaration//GEN-END:variables
}
